/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsserviceaplicare;

import fungsi.BPJSSecurityUtil;
import fungsi.HttpRequestUtil;
import fungsi.JsonUtil;
import fungsi.LogTableModel;
import fungsi.koneksiDB;
import fungsi.logger.LogType;
import fungsi.logger.SystemLogger;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalTime;
import java.util.Map;
import javax.swing.Timer;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private String URL = "", link = "";
    private final String kodeppk = Sequel.cariIsi("select setting.kode_ppk from setting");
    private HttpHeaders headers;
    private BPJSSecurityUtil security = new BPJSSecurityUtil(koneksiDB.CONSIDAPIAPLICARE(), koneksiDB.SECRETKEYAPIAPLICARE());
    private Map<String, Object> metadata;
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceAplicare.logPath, "app-log");

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        try {
            link = koneksiDB.URLAPIAPLICARE();
        } catch (Exception e) {
            System.out.println("E : " + e);
            SystemLogger.error(e);
        }

        this.setSize(390, 340);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(210);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(210);

        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Aplicare");

        jButton1.setText("Keluar");
        jButton1.setMaximumSize(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(16, 16));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 402));

        jTable1.setModel(userTableModel);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int menit;
            private int detik;

            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime now = LocalTime.now();
                menit = now.getMinute();
                detik = now.getSecond();
                if (now.equals(LocalTime.of(0, 4, 30))) {
                    userTableModel.resetData();
                    SystemLogger.reconfigure();
                }

                if ((menit % 5 == 0) && (detik == 0)) {
                    try {
                        koneksi = koneksiDB.condb();
                        userTableModel.tambahData("Memulai update aplicare");
                        try (PreparedStatement ps = koneksi.prepareStatement(
                                "select aplicare_ketersediaan_kamar.kode_kelas_aplicare,aplicare_ketersediaan_kamar.kd_bangsal,"
                                + "bangsal.nm_bangsal,aplicare_ketersediaan_kamar.kelas,aplicare_ketersediaan_kamar.kapasitas,"
                                + "aplicare_ketersediaan_kamar.tersedia,aplicare_ketersediaan_kamar.tersediapria,"
                                + "aplicare_ketersediaan_kamar.tersediawanita,aplicare_ketersediaan_kamar.tersediapriawanita "
                                + "from aplicare_ketersediaan_kamar inner join bangsal on aplicare_ketersediaan_kamar.kd_bangsal=bangsal.kd_bangsal"); ResultSet rs = ps.executeQuery();) {
                            SystemLogger.sql(ps.toString());

                            while (rs.next()) {
                                userTableModel.tambahData("Mengirimkan kamar " + rs.getString("kode_kelas_aplicare") + " " + rs.getString("nm_bangsal"));
                                try {
                                    BPJSSecurityUtil.SignatureResult resultSignature = security.generateSignaturePair();
                                    headers = new HttpHeaders();
                                    headers.setContentType(MediaType.APPLICATION_JSON);
                                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIAPLICARE());
                                    headers.add("X-Timestamp", String.valueOf(resultSignature.timestamp));
                                    headers.add("X-Signature", resultSignature.signature);

                                    int tersedia = Integer.parseInt(Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and status='KOSONG'"));
                                    int kapasitas = Integer.parseInt(Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "'"));

                                    String requestJson = JsonUtil.createObject()
                                            .put("kodekelas", rs.getString("kode_kelas_aplicare"))
                                            .put("koderuang", rs.getString("kd_bangsal"))
                                            .put("namaruang", rs.getString("nm_bangsal"))
                                            .put("kapasitas", kapasitas)
                                            .put("tersedia", tersedia)
                                            .put("tersediapria", tersedia)
                                            .put("tersediawanita", tersedia)
                                            .put("tersediapriawanita", tersedia)
                                            .build();

                                    URL = link + "/rest/bed/update/" + kodeppk;

                                    HttpRequestUtil http = HttpRequestUtil.getInstance();
                                    ResponseEntity<Map> responseEntity = http.exchange(URL, HttpMethod.POST, requestJson, Map.class, headers);
                                    if (responseEntity == null) {
                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                    }

                                    Map responseMap = responseEntity.getBody();
                                    if (responseMap != null && responseMap.containsKey("metadata")) {
                                        userTableModel.tambahData("Request URL: " + URL, LogType.HTTP);
                                        userTableModel.tambahData("Request JSON: " + requestJson, LogType.HTTP);
                                    }

                                    metadata = (Map<String, Object>) responseEntity.getBody().get("metadata");

                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("message").toString());
                                } catch (Exception ex) {
                                    System.out.println("Notifikasi Bridging : " + ex);
                                    SystemLogger.error(ex);
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : " + ex);
                            SystemLogger.error(ex);
                        }
                        userTableModel.tambahData("Proses update selesai");
                    } catch (Exception ez) {
                        System.out.println("Notif : " + ez);
                        SystemLogger.error(ez);
                    }
                }
            }
        };
        new Timer(1000, taskPerformer).start();
    }
}
