/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsserviceaplicare;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.BPJSApiAplicare;
import fungsi.LogTableModel;
import fungsi.koneksiDB;
import fungsi.logger.LogType;
import fungsi.logger.SystemLogger;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private String requestJson;
    private String URL = "";
    private final String kodeppk = Sequel.cariIsi("select setting.kode_ppk from setting");
    private final BPJSApiAplicare api = new BPJSApiAplicare();
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private final ObjectMapper mapper = new ObjectMapper();
    private JsonNode root;
    private JsonNode nameNode;
    private PreparedStatement ps;
    private ResultSet rs;
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceAplicare.logPath, "app-log");

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();

        this.setSize(390, 340);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(210);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(210);

        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Aplicare");

        jButton1.setText("Keluar");
        jButton1.setMaximumSize(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(16, 16));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 402));

        jTable1.setModel(userTableModel);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            @Override
            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date now = Calendar.getInstance().getTime();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                nilai_jam = now.getHours();
                nilai_menit = now.getMinutes();
                nilai_detik = now.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                if (jam.equals("01") && menit.equals("01") && detik.equals("01")) {
                    userTableModel.resetData();
                    SystemLogger.reconfigure();
                }

                if ((nilai_jam % 4 == 0) && (detik.equals("01") && menit.equals("01"))) {
                    try {
                        koneksi = koneksiDB.condb();
                        userTableModel.tambahData("Memulai update aplicare\n");
                        ps = koneksi.prepareStatement(
                                "select aplicare_ketersediaan_kamar.kode_kelas_aplicare,aplicare_ketersediaan_kamar.kd_bangsal,"
                                + "bangsal.nm_bangsal,aplicare_ketersediaan_kamar.kelas,aplicare_ketersediaan_kamar.kapasitas,"
                                + "aplicare_ketersediaan_kamar.tersedia,aplicare_ketersediaan_kamar.tersediapria,"
                                + "aplicare_ketersediaan_kamar.tersediawanita,aplicare_ketersediaan_kamar.tersediapriawanita "
                                + "from aplicare_ketersediaan_kamar inner join bangsal on aplicare_ketersediaan_kamar.kd_bangsal=bangsal.kd_bangsal");
                        try {
                            rs = ps.executeQuery();
                            SystemLogger.sql(rs.toString());
                            while (rs.next()) {
                                userTableModel.tambahData("Mengirimkan kamar " + rs.getString("kode_kelas_aplicare") + " " + rs.getString("nm_bangsal") + "\n");
                                try {
                                    headers = new HttpHeaders();
                                    headers.setContentType(MediaType.APPLICATION_JSON);
                                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIAPLICARE());
                                    headers.add("X-Timestamp", String.valueOf(api.GetUTCdatetimeAsString()));
                                    headers.add("X-Signature", api.getHmac());
                                    requestJson = "{\"kodekelas\":\"" + rs.getString("kode_kelas_aplicare") + "\", "
                                            + "\"koderuang\":\"" + rs.getString("kd_bangsal") + "\","
                                            + "\"namaruang\":\"" + rs.getString("nm_bangsal") + "\","
                                            + "\"kapasitas\":\"" + Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "'") + "\","
                                            + "\"tersedia\":\"" + Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and status='KOSONG'") + "\","
                                            + "\"tersediapria\":\"" + Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and status='KOSONG'") + "\","
                                            + "\"tersediawanita\":\"" + Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and status='KOSONG'") + "\","
                                            + "\"tersediapriawanita\":\"" + Sequel.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='" + rs.getString("kelas") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and status='KOSONG'") + "\""
                                            + "}";
                                    userTableModel.tambahData("JSON dikirim : " + requestJson + "\n");
                                    requestEntity = new HttpEntity(requestJson, headers);
                                    URL = URL + "/rest/bed/update/" + kodeppk;
                                    root = mapper.readTree(api.getRest().exchange(URL, HttpMethod.POST, requestEntity, String.class).getBody());
                                    System.out.println("Request URL : " + URL);
                                    userTableModel.tambahData("Request JSON : " + requestJson);
                                    userTableModel.tambahData("Request URL : " + URL, LogType.HTTP);
                                    nameNode = root.path("metadata");
                                    userTableModel.tambahData("respon WS BPJS : " + nameNode.path("message").asText() + "\n");
                                } catch (Exception ex) {
                                    System.out.println("Notifikasi Bridging : " + ex);
                                    SystemLogger.error(ex);
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : " + ex);
                            SystemLogger.error(ex);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }
                        userTableModel.tambahData("Proses update selesai\n");
                    } catch (Exception ez) {
                        System.out.println("Notif : " + ez);
                        SystemLogger.error(ez);
                    }
                }
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
}
