/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package khanzaconfig;

import java.awt.event.ActionEvent;
import java.io.File;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import khanzaconfig.aessecurity.EnkripsiAES;
import org.jdesktop.swingx.prompt.PromptSupport;
import org.w3c.dom.Comment;
import org.w3c.dom.Document;
import org.w3c.dom.DocumentType;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author malifnasrulloh
 */
public class KhanzaConfig extends JFrame {

    private LinkedHashMap<String, String> prop = new LinkedHashMap<>();
    private File loadedFile;
    private final DefaultTableModel tableModel;
    private final JFileChooser fc = new JFileChooser();
    private boolean isEncrypted;

    /**
     * Creates new form NewJPanel
     */
    public KhanzaConfig() {
        initComponents();

        PromptSupport.setPrompt("Search by Key", jTextField2);

        fc.setCurrentDirectory(new File("."));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileFilter(new FileFilter() {
            @Override
            public String getDescription() {
                return "XML Files (*.xml)";
            }

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    String filename = f.getName().toLowerCase();
                    return filename.endsWith(".xml") || filename.endsWith(".xml");
                }
            }
        });

        tableModel = (DefaultTableModel) jTable1.getModel();

        jTable1.getSelectionModel().addListSelectionListener((e) -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = jTable1.getSelectedRow();

                if (selectedRow > -1) {
                    String key = jTable1.getModel().getValueAt(selectedRow, 0).toString();
                    String value = jTable1.getModel().getValueAt(selectedRow, 1).toString();
                    isEncrypted = (boolean) jTable1.getModel().getValueAt(selectedRow, 2);

                    jTextField3.setText(key);
                    jTextField1.setText(isEncrypted(value) ? EnkripsiAES.decrypt(value) : value);
                }
            }
        });

        jTextField2.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                refreshTableData();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                refreshTableData();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                refreshTableData();
            }
        });

    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new KhanzaConfig().setVisible(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 450));
        setSize(new java.awt.Dimension(500, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Key", "Value", "Encrypted"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextField3.setText("");
        jTextField3.setPreferredSize(new java.awt.Dimension(120, 22));
        jTextField3.setToolTipText("Key");
        jPanel1.add(jTextField3);

        jTextField1.setText("");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 22));
        jTextField1.setToolTipText("Value");
        jPanel1.add(jTextField1);

        jButton2.setText("Simpan");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        jButton3.setText("Hapus");
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jTextField2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Load File");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1, java.awt.BorderLayout.LINE_START);

        jLabel1.setText("Loaded File: ");
        jLabel1.setAutoscrolls(true);
        jLabel1.setFocusable(false);
        jLabel1.setName(""); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadFile(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveConfig(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public void loadFile(ActionEvent e) {
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                loadedFile = fc.getSelectedFile();
                jLabel1.setText("Loaded file: " + loadedFile.getName());
                jLabel1.setToolTipText(loadedFile.getAbsolutePath());

                refreshTableData();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            System.out.println("Open command cancelled by user." + "");
        }
    }

    public void refreshTableData() {
        try {
            SwingUtilities.invokeLater(() -> tableModel.setRowCount(0));

            prop = parseKeysAndValuesFromXML(loadedFile);
            List<String> keys = new ArrayList<>(prop.keySet());  // Preserves order from LinkedHashMap

            String[] filteredKey = keys.stream()
                    .filter(key -> key.toLowerCase().contains(jTextField2.getText().toLowerCase()))
                    .toArray(String[]::new);

            for (String key : filteredKey) {
                String value = prop.get(key);

                SwingUtilities.invokeLater(() -> {
                    Object[] row = {key, value, isEncrypted(value)};
                    tableModel.addRow(row);
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void saveConfig(ActionEvent e) {
        String key = jTextField3.getText().trim();
        try {
            if (!key.isBlank()) {
                String value = jTextField1.getText().trim();
                prop.put(key, isEncrypted ? EnkripsiAES.encrypt(value) : value);

                saveToXML(loadedFile, prop);
                jTextField1.setText("");
                jTextField3.setText("");

                JOptionPane.showMessageDialog(this, "Konfigurasi berhasil disimpan");
                refreshTableData();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private LinkedHashMap<String, String> parseKeysAndValuesFromXML(File file) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.parse(file);
        NodeList entries = doc.getElementsByTagName("entry");
        LinkedHashMap<String, String> map = new LinkedHashMap<>();
        for (int i = 0; i < entries.getLength(); i++) {
            Element entry = (Element) entries.item(i);
            String key = entry.getAttribute("key");
            String value = entry.getTextContent();
            map.put(key, value);
        }
        return map;
    }

    private void saveToXML(File file, LinkedHashMap<String, String> map) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.newDocument();

        Element root = doc.createElement("properties");
        doc.appendChild(root);

        Comment comment = doc.createComment("KhanzaConfig");
        root.appendChild(comment);
        for (Map.Entry<String, String> entry : map.entrySet()) {
            Element entryElem = doc.createElement("entry");
            entryElem.setAttribute("key", entry.getKey());
            entryElem.setTextContent(entry.getValue());
            root.appendChild(entryElem);
        }

        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        Transformer transformer = transformerFactory.newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");
        transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");
        transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
        transformer.setOutputProperty(OutputKeys.STANDALONE, "no");
        transformer.setOutputProperty(OutputKeys.DOCTYPE_SYSTEM, "http://java.sun.com/dtd/properties.dtd");

        DOMSource source = new DOMSource(doc);
        StreamResult result = new StreamResult(file);
        transformer.transform(source, result);
    }

    private boolean isEncrypted(String string) {
        try {
            EnkripsiAES.decrypt(string);
            return true;
        } catch (Exception e) {
        }
        return false;
    }

}
