/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsservicesatusehat;

import fungsi.HttpRequestUtil;
import fungsi.JsonUtil;
import fungsi.LogTableModel;
import fungsi.SatuSehatHelper;
import fungsi.fhir.EncounterService;
import fungsi.fhir.FHIRPayload;
import fungsi.koneksiDB;
import fungsi.logger.LogType;
import fungsi.logger.SystemLogger;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.Timer;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import tools.jackson.databind.JsonNode;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private String URL = "", requestJson = "", link = "", iddokter = "", idpasien = "", sistole = "0", diastole = "0", signa1 = "1", signa2 = "1", idrequest = "";
    private HttpHeaders headers;
    private JsonNode responseBody;
    private ResponseEntity<JsonNode> response;
    private PreparedStatement ps;
    private ResultSet rs;
    private String[] arrSplit;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private Date dateTime = new Date();
    private SatuSehatHelper satuSehatHelper = new SatuSehatHelper(koneksiDB.CLIENTIDSATUSEHAT(), koneksiDB.SECRETKEYSATUSEHAT(), koneksiDB.IDSATUSEHAT(), koneksiDB.URLAUTHSATUSEHAT(), koneksiDB.URLFHIRSATUSEHAT());
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceSatuSehat.logPath, "app-log");

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        try {
            link = koneksiDB.URLFHIRSATUSEHAT();
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            SystemLogger.error(e);
        }

        this.setSize(490, 340);

        dateTime = new Date();
        Tanggal1.setText(dateFormat.format(dateTime));
        Tanggal2.setText(dateFormat.format(dateTime));

        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tanggal2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Satu Sehat");

        jTable1.setModel(userTableModel);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(new java.awt.Dimension(327, 33));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tanggal :");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel1.add(jLabel1);

        Tanggal1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal1);

        jLabel3.setText("s.d.");
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 23));
        jPanel1.add(jLabel3);

        Tanggal2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal2);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tanggal1;
    private javax.swing.JTextField Tanggal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private ResponseEntity<JsonNode> exchangeInteroperabilitas(String URL, String requestJson, HttpMethod httpMethod) {
        try {
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("Authorization", "Bearer " + satuSehatHelper.getAuthToken());

            HttpRequestUtil http = HttpRequestUtil.getInstance();
            ResponseEntity<JsonNode> responseEntity = http.exchange(URL, httpMethod, requestJson, JsonNode.class, headers);

            if (responseEntity == null) {
                return null;
            }

            userTableModel.tambahData("Request URL: " + URL, LogType.HTTP);
            userTableModel.tambahData("Request JSON: " + requestJson, LogType.HTTP);

            return responseEntity;
        } catch (Exception e) {
            return null;
        }
    }

    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int jam;
            private int menit;
            private int detik;

            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime now = LocalTime.now();
                jam = now.getHour();
                menit = now.getMinute();
                detik = now.getSecond();
                if (now.equals(LocalTime.of(0, 9, 30))) {
                    userTableModel.resetData();
                    SystemLogger.reconfigure();

                    dateTime = new Date();
                    Tanggal1.setText(dateFormat.format(dateTime));
                    Tanggal2.setText(dateFormat.format(dateTime));

//                    medication();
                }

//                if ((detik == 0) && (menit % 4 == 0)) {
//                    encounter2();
//                    servicerequestradiologi();
//                }
                if ((menit % 10 == 0) && (detik == 0)) {
                    encounter();
//                    observationTTV();
//                    vaksin();
//                    prosedur();
//                    condition();
//                    clinicalimpression();
//                    dietgizi();
//                    medicationrequest();
//                    medicationdispense();
//                    medicationstatement();
//                    specimenradiologi();
//                    observationradiologi();
//                    diagnosticreportradiologi();
//                    servicerequestlabpk();
//                    servicerequestlabmb();
//                    specimenlabpk();
//                    specimenlabmb();
//                    observationlabpk();
//                    observationlabmb();
//                    diagnosticreportlabpk();
//                    diagnosticreportlabmb();
//                    careplan();
                }
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }

    private void encounter() {
        //kirim encounter
        try {
            ps = koneksi.prepareStatement(
                    "select reg_periksa.tgl_registrasi,reg_periksa.jam_reg,reg_periksa.no_rawat,pasien.nm_pasien,pasien.no_ktp,"
                    + "pegawai.nama,pegawai.no_ktp as ktpdokter,poliklinik.nm_poli,satu_sehat_mapping_lokasi_ralan.id_lokasi_satusehat,"
                    + "reg_periksa.status_lanjut,concat(reg_periksa.tgl_registrasi,'T',reg_periksa.jam_reg,'+07:00') as pulang,ifnull(satu_sehat_encounter.id_encounter,'') as id_encounter "
                    + "from reg_periksa inner join pasien on reg_periksa.no_rkm_medis=pasien.no_rkm_medis inner join pegawai on pegawai.nik=reg_periksa.kd_dokter "
                    + "inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli inner join satu_sehat_mapping_lokasi_ralan on satu_sehat_mapping_lokasi_ralan.kd_poli=poliklinik.kd_poli "
                    + "left join satu_sehat_encounter on satu_sehat_encounter.no_rawat=reg_periksa.no_rawat "
                    + "where reg_periksa.status_bayar='Sudah Bayar' and reg_periksa.tgl_registrasi between ? and ?");
            try {
                ps.setString(1, Tanggal1.getText());
                ps.setString(2, Tanggal2.getText());
                rs = ps.executeQuery();
                SystemLogger.sql(ps);
                while (rs.next()) {
                    if ((!rs.getString("no_ktp").equals("")) && (!rs.getString("ktpdokter").equals("")) && rs.getString("id_encounter").equals("")) {
                        try {
                            iddokter = satuSehatHelper.getPractitionerIDByNIK(rs.getString("ktpdokter"));
                            idpasien = satuSehatHelper.getPatientIDByNIK(rs.getString("no_ktp"));
                            try {
                                requestJson = FHIRPayload.from(
                                        EncounterService.buildEncounter(
                                                JsonUtil.createObject()
                                                        .put("code_class", rs.getString("status_lanjut").equals("Ralan") ? "AMB" : "IMP")
                                                        .put("display_class", rs.getString("status_lanjut").equals("Ralan") ? "ambulatory" : "inpatient encounter")
                                                        .put("id_pasien", idpasien)
                                                        .put("nm_pasien", rs.getString("nm_pasien"))
                                                        .put("id_dokter", iddokter)
                                                        .put("nama_dokter", rs.getString("nama"))
                                                        .put("tgl_registrasi", rs.getString("tgl_registrasi"))
                                                        .put("jam_reg", rs.getString("jam_reg"))
                                                        .put("pulang", rs.getString("pulang"))
                                                        .put("id_lokasi", rs.getString("id_lokasi_satusehat"))
                                                        .put("nm_poli", rs.getString("nm_poli"))
                                                        .put("no_rawat", rs.getString("no_rawat"))
                                                        .put("service_provider_id", koneksiDB.IDSATUSEHAT())
                                                        .put("status", "arrived")
                                                        .getNode())).toJson();

                                URL = link + "/Encounter";

                                response = exchangeInteroperabilitas(URL, requestJson, HttpMethod.POST);
                                if (response == null) {
                                    throw new IllegalStateException(String.format("Response {'%s'} kosong / null", URL));
                                }

                                responseBody = response.getBody();
                                userTableModel.tambahData("Result JSON : " + responseBody.toString());

                                if (!responseBody.path("id").asString().equals("")) {
                                    Sequel.menyimpan2("satu_sehat_encounter", "?,?", "No.Rawat", 2, new String[]{
                                        rs.getString("no_rawat"), responseBody.path("id").asString()
                                    });
                                }
                            } catch (Exception ea) {
                                userTableModel.tambahData("Notifikasi Bridging : " + ea, LogType.EXCEPTION);
                                SystemLogger.error(ea);
                            }
                        } catch (Exception ef) {
                            System.out.println("Notifikasi : " + ef);
                            SystemLogger.error(ef);
                        }
                    } else {
                        try {
                            iddokter = satuSehatHelper.getPractitionerIDByNIK(rs.getString("ktpdokter"));
                            idpasien = satuSehatHelper.getPatientIDByNIK(rs.getString("no_ktp"));
                            try {
                                requestJson = FHIRPayload.from(
                                        EncounterService.buildEncounter(
                                                JsonUtil.createObject()
                                                        .put("id_encounter", rs.getString("id_encounter"))
                                                        .put("status", "finished")
                                                        .put("code_class", rs.getString("status_lanjut").equals("Ralan") ? "AMB" : "IMP")
                                                        .put("display_class", rs.getString("status_lanjut").equals("Ralan") ? "ambulatory" : "inpatient encounter")
                                                        .put("id_pasien", idpasien)
                                                        .put("nm_pasien", rs.getString("nm_pasien"))
                                                        .put("id_dokter", iddokter)
                                                        .put("nama_dokter", rs.getString("nama"))
                                                        .put("tgl_registrasi", rs.getString("tgl_registrasi"))
                                                        .put("jam_reg", rs.getString("jam_reg"))
                                                        .put("pulang", rs.getString("pulang"))
                                                        .put("id_lokasi", rs.getString("id_lokasi_satusehat"))
                                                        .put("nm_poli", rs.getString("nm_poli"))
                                                        .put("no_rawat", rs.getString("no_rawat"))
                                                        .put("service_provider_id", koneksiDB.IDSATUSEHAT())
                                                        .getNode())).toJson();

                                URL = link + "/Encounter/" + rs.getString("id_encounter");

                                response = exchangeInteroperabilitas(URL, requestJson, HttpMethod.PUT);
                                if (response == null) {
                                    throw new IllegalStateException(String.format("Response {'%s'} kosong / null", URL));
                                }

                                responseBody = response.getBody();
                                userTableModel.tambahData("Result JSON : " + responseBody.toString());

                                if (!responseBody.path("id").asString().equals("")) {
                                    Sequel.menyimpan2("satu_sehat_encounter", "?,?", "No.Rawat", 2, new String[]{
                                        rs.getString("no_rawat"), responseBody.path("id").asString()
                                    });
                                }
                            } catch (Exception ea) {
                                userTableModel.tambahData("Notifikasi Bridging : " + ea, LogType.EXCEPTION);
                                SystemLogger.error(ea);
                            }
                        } catch (Exception ef) {
                            System.out.println("Notifikasi : " + ef);
                            SystemLogger.error(ef);
                        }
                    }
                }
            } catch (Exception ex) {
                System.out.println("Notif : " + ex);
                SystemLogger.error(ex);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception ez) {
            System.out.println("Notifikasi : " + ez);
            SystemLogger.error(ez);
        }
    }

    private void encounter2() {
        //kirim encounter
        try {
            ps = koneksi.prepareStatement(
                    "select reg_periksa.tgl_registrasi,reg_periksa.jam_reg,reg_periksa.no_rawat,pasien.nm_pasien,pasien.no_ktp,"
                    + "pegawai.nama,pegawai.no_ktp as ktpdokter,poliklinik.nm_poli,satu_sehat_mapping_lokasi_ralan.id_lokasi_satusehat,"
                    + "reg_periksa.status_lanjut,concat(reg_periksa.tgl_registrasi,'T',reg_periksa.jam_reg,'+07:00') as pulang,ifnull(satu_sehat_encounter.id_encounter,'') as id_encounter "
                    + "from reg_periksa inner join pasien on reg_periksa.no_rkm_medis=pasien.no_rkm_medis inner join pegawai on pegawai.nik=reg_periksa.kd_dokter "
                    + "inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli inner join satu_sehat_mapping_lokasi_ralan on satu_sehat_mapping_lokasi_ralan.kd_poli=poliklinik.kd_poli "
                    + "left join satu_sehat_encounter on satu_sehat_encounter.no_rawat=reg_periksa.no_rawat "
                    + "inner join permintaan_radiologi on permintaan_radiologi.no_rawat=reg_periksa.no_rawat "
                    + "where reg_periksa.tgl_registrasi between ? and ? group by reg_periksa.no_rawat");
            try {
                ps.setString(1, Tanggal1.getText());
                ps.setString(2, Tanggal2.getText());
                rs = ps.executeQuery();
                SystemLogger.sql(ps);
                while (rs.next()) {
                    if ((!rs.getString("no_ktp").equals("")) && (!rs.getString("ktpdokter").equals("")) && rs.getString("id_encounter").equals("")) {
                        try {
                            iddokter = satuSehatHelper.getPractitionerIDByNIK(rs.getString("ktpdokter"));
                            idpasien = satuSehatHelper.getPatientIDByNIK(rs.getString("no_ktp"));
                            try {
                                requestJson = FHIRPayload.from(
                                        EncounterService.buildEncounter(
                                                JsonUtil.createObject()
                                                        .put("status", "arrived")
                                                        .put("code_class", rs.getString("status_lanjut").equals("Ralan") ? "AMB" : "IMP")
                                                        .put("display_class", rs.getString("status_lanjut").equals("Ralan") ? "ambulatory" : "inpatient encounter")
                                                        .put("id_pasien", idpasien)
                                                        .put("nm_pasien", rs.getString("nm_pasien"))
                                                        .put("id_dokter", iddokter)
                                                        .put("nama_dokter", rs.getString("nama"))
                                                        .put("tgl_registrasi", rs.getString("tgl_registrasi"))
                                                        .put("jam_reg", rs.getString("jam_reg"))
                                                        .put("pulang", rs.getString("pulang"))
                                                        .put("id_lokasi", rs.getString("id_lokasi_satusehat"))
                                                        .put("nm_poli", rs.getString("nm_poli"))
                                                        .put("no_rawat", rs.getString("no_rawat"))
                                                        .put("service_provider_id", koneksiDB.IDSATUSEHAT())
                                                        .getNode())).toJson();
                                requestJson = FHIRPayload.from(EncounterService.buildEncounter(JsonUtil.createObject().getNode())).toJson();

                                URL = link + "/Encounter";

                                response = exchangeInteroperabilitas(URL, requestJson, HttpMethod.POST);
                                if (response == null) {
                                    throw new IllegalStateException(String.format("Response {'%s'} kosong / null", URL));
                                }

                                responseBody = response.getBody();
                                userTableModel.tambahData("Result JSON : " + responseBody.toString());

                                if (!responseBody.path("id").asString().equals("")) {
                                    Sequel.menyimpan2("satu_sehat_encounter", "?,?", "No.Rawat", 2, new String[]{
                                        rs.getString("no_rawat"), responseBody.path("id").asString()
                                    });
                                }
                            } catch (Exception ea) {
                                userTableModel.tambahData("Notifikasi Bridging : " + ea, LogType.EXCEPTION);
                                SystemLogger.error(ea);
                            }
                        } catch (Exception ef) {
                            System.out.println("Notifikasi : " + ef);
                            SystemLogger.error(ef);
                        }
                    }
                }
            } catch (Exception ex) {
                System.out.println("Notif : " + ex);
                SystemLogger.error(ex);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception ez) {
            System.out.println("Notifikasi : " + ez);
            SystemLogger.error(ez);
        }
    }
}
