/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsservicemobilejkn;

import fungsi.BPJSSecurityUtil;
import fungsi.HttpRequestUtil;
import fungsi.JsonUtil;
import fungsi.LogTableModel;
import fungsi.koneksiDB;
import fungsi.logger.LogType;
import fungsi.logger.SystemLogger;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import javax.swing.Timer;
import org.apache.commons.lang3.StringUtils;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private String requestJson, URL = "", link = "", datajam = "", hari = "", noresep = "", kodepoli = "", kodedokter = "", kodebpjs = Sequel.cariIsi("select password_asuransi.kd_pj from password_asuransi");
    private HttpHeaders headers;
    private PreparedStatement ps, ps2;
    private ResultSet rs, rs2;
    private Calendar cal = Calendar.getInstance();
    private int day = cal.get(Calendar.DAY_OF_WEEK);
    private SimpleDateFormat dateTimeFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private Date parsedDateTime;
    private Date dateTime = new Date();
    private BPJSSecurityUtil security = new BPJSSecurityUtil(koneksiDB.CONSIDAPIMOBILEJKN(), koneksiDB.SECRETKEYAPIMOBILEJKN());
    private ResponseEntity<Map> response;
    private Map<String, Object> metadata;
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceMobileJKN.logPath, "app-log");

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        try {
            link = koneksiDB.URLAPIMOBILEJKN();
        } catch (Exception e) {
            System.out.println("E : " + e);
            SystemLogger.error(e);
        }

        this.setSize(490, 340);

        dateTime = new Date();
        Tanggal1.setText(dateFormat.format(dateTime));
        Tanggal2.setText(dateFormat.format(dateTime));

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(210);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(210);
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tanggal2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Mobile JKN");

        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(new java.awt.Dimension(327, 33));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tanggal :");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel1.add(jLabel1);

        Tanggal1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal1);

        jLabel3.setText("s.d.");
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 23));
        jPanel1.add(jLabel3);

        Tanggal2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(Tanggal2);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 402));

        jTable1.setModel(userTableModel);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tanggal1;
    private javax.swing.JTextField Tanggal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private ResponseEntity<Map> exchangeMobileJKN(String URL, String requestJson) {
        try {
            BPJSSecurityUtil.SignatureResult resultSignature = security.generateSignaturePair();
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("x-cons-id", koneksiDB.CONSIDAPIMOBILEJKN());
            headers.add("x-timestamp", String.valueOf(resultSignature.timestamp));
            headers.add("x-signature", resultSignature.signature);
            headers.add("user_key", koneksiDB.USERKEYAPIMOBILEJKN());

            HttpRequestUtil http = HttpRequestUtil.getInstance();
            ResponseEntity<Map> responseEntity = http.exchange(URL, HttpMethod.POST, requestJson, Map.class, headers);

            if (responseEntity == null) {
                return null;
            }

            Map responseMap = responseEntity.getBody();
            if (responseMap != null && responseMap.containsKey("metadata")) {
                userTableModel.tambahData("Request URL: " + URL, LogType.HTTP);
                userTableModel.tambahData("Request JSON: " + requestJson, LogType.HTTP);
            }
            return responseEntity;
        } catch (Exception e) {
            return null;
        }
    }

    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int menit, detik;
            private final String[] hariIndonesia = {
                "AKHAD",
                "SENIN",
                "SELASA",
                "RABU",
                "KAMIS",
                "JUMAT",
                "SABTU"
            };

            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime now = LocalTime.now();
                menit = now.getMinute();
                detik = now.getSecond();
                if (now.equals(LocalTime.of(0, 9, 30))) {
                    userTableModel.resetData();
                    SystemLogger.reconfigure();

                    dateTime = new Date();
                    Tanggal1.setText(dateFormat.format(dateTime));
                    Tanggal2.setText(dateFormat.format(dateTime));
                }

                if ((menit % 10 == 0) && (detik == 0)) {
                    day = cal.get(Calendar.DAY_OF_WEEK);
                    hari = hariIndonesia[day - 1];

                    try {
                        koneksi = koneksiDB.condb();
                        userTableModel.tambahData("Menjalankan WS tambah antrian Mobile JKN Pasien BPJS");

                        //pasien JKN
                        ps = koneksi.prepareStatement(
                                "SELECT referensi_mobilejkn_bpjs.nobooking,referensi_mobilejkn_bpjs.no_rawat,reg_periksa.no_rkm_medis,pasien.nm_pasien,referensi_mobilejkn_bpjs.nohp,referensi_mobilejkn_bpjs.nomorkartu,"
                                + "referensi_mobilejkn_bpjs.nik,referensi_mobilejkn_bpjs.tanggalperiksa,poliklinik.nm_poli,dokter.nm_dokter,referensi_mobilejkn_bpjs.jampraktek,"
                                + "referensi_mobilejkn_bpjs.jeniskunjungan,referensi_mobilejkn_bpjs.nomorreferensi,referensi_mobilejkn_bpjs.status,referensi_mobilejkn_bpjs.validasi,"
                                + "referensi_mobilejkn_bpjs.kodepoli,referensi_mobilejkn_bpjs.pasienbaru,referensi_mobilejkn_bpjs.kodedokter,referensi_mobilejkn_bpjs.jampraktek,"
                                + "referensi_mobilejkn_bpjs.nomorantrean,referensi_mobilejkn_bpjs.angkaantrean,referensi_mobilejkn_bpjs.estimasidilayani,referensi_mobilejkn_bpjs.sisakuotajkn,"
                                + "referensi_mobilejkn_bpjs.kuotajkn,referensi_mobilejkn_bpjs.sisakuotanonjkn,referensi_mobilejkn_bpjs.kuotanonjkn "
                                + "FROM referensi_mobilejkn_bpjs INNER JOIN reg_periksa ON referensi_mobilejkn_bpjs.no_rawat=reg_periksa.no_rawat "
                                + "INNER JOIN pasien ON reg_periksa.no_rkm_medis=pasien.no_rkm_medis "
                                + "INNER JOIN poliklinik ON reg_periksa.kd_poli=poliklinik.kd_poli "
                                + "INNER JOIN dokter ON reg_periksa.kd_dokter=dokter.kd_dokter "
                                + "WHERE referensi_mobilejkn_bpjs.statuskirim='Belum' and referensi_mobilejkn_bpjs.tanggalperiksa between " + (Tanggal1.getText().equals(Tanggal2.getText()) ? "SUBDATE('" + Tanggal2.getText() + "',INTERVAL 6 DAY) and '" + Tanggal2.getText() + "'" : "'" + Tanggal1.getText() + "' and '" + Tanggal2.getText() + "'")
                                + "order by referensi_mobilejkn_bpjs.tanggalperiksa");
                        try {
                            rs = ps.executeQuery();
                            SystemLogger.sql(ps.toString());
                            while (rs.next()) {
                                try {
                                    requestJson = JsonUtil.createObject()
                                            .put("kodebooking", rs.getString("nobooking"))
                                            .put("jenispasien", "JKN")
                                            .put("nomorkartu", rs.getString("nomorkartu"))
                                            .put("nik", rs.getString("nik"))
                                            .put("nohp", rs.getString("nohp"))
                                            .put("kodepoli", rs.getString("kodepoli"))
                                            .put("namapoli", rs.getString("nm_poli"))
                                            .put("pasienbaru", rs.getString("pasienbaru"))
                                            .put("norm", rs.getString("no_rkm_medis"))
                                            .put("tanggalperiksa", rs.getString("tanggalperiksa"))
                                            .put("kodedokter", rs.getString("kodedokter"))
                                            .put("namadokter", rs.getString("nm_dokter"))
                                            .put("jampraktek", rs.getString("jampraktek"))
                                            .put("jeniskunjungan", rs.getString("jeniskunjungan").substring(0, 1))
                                            .put("nomorreferensi", rs.getString("nomorreferensi"))
                                            .put("nomorantrean", rs.getString("nomorantrean"))
                                            .put("angkaantrean", Integer.parseInt(rs.getString("angkaantrean")))
                                            .put("estimasidilayani", rs.getString("estimasidilayani"))
                                            .put("sisakuotajkn", rs.getString("sisakuotajkn"))
                                            .put("kuotajkn", rs.getString("kuotajkn"))
                                            .put("sisakuotanonjkn", rs.getString("sisakuotanonjkn"))
                                            .put("kuotanonjkn", rs.getString("kuotanonjkn"))
                                            .put("keterangan", "Peserta harap 30 menit lebih awal guna pencatatan administrasi.")
                                            .build();

                                    URL = link + "/antrean/add";

                                    response = exchangeMobileJKN(URL, requestJson);
                                    if (response == null) {
                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                    }

                                    metadata = (Map<String, Object>) response.getBody().get("metadata");

                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("message").toString());

                                    if (metadata.get("code").toString().equals("200") || metadata.get("code").toString().equals("208") || metadata.get("message").toString().equals("Ok")) {
                                        Sequel.queryu2("update referensi_mobilejkn_bpjs set statuskirim='Sudah' where nobooking='" + rs.getString("nobooking") + "'");
                                    }
                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                } catch (Exception ex) {
                                    System.out.println("Notifikasi Bridging : " + ex);
                                    SystemLogger.error(ex);
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif : " + ex);
                            SystemLogger.error(ex);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }

                        userTableModel.tambahData("Menjalankan WS batal antrian Mobile JKN Pasien BPJS");
                        ps = koneksi.prepareStatement(
                                "SELECT * FROM referensi_mobilejkn_bpjs_batal where referensi_mobilejkn_bpjs_batal.statuskirim='Belum' and referensi_mobilejkn_bpjs_batal.tanggalbatal between " + (Tanggal1.getText().equals(Tanggal2.getText()) ? "SUBDATE('" + Tanggal2.getText() + "',INTERVAL 6 DAY) and '" + Tanggal2.getText() + "'" : "'" + Tanggal1.getText() + "' and '" + Tanggal2.getText() + "'"));
                        try {
                            rs = ps.executeQuery();
                            SystemLogger.sql(ps.toString());
                            while (rs.next()) {
                                try {
                                    requestJson = JsonUtil.createObject()
                                            .put("kodebooking", rs.getString("nobooking"))
                                            .put("keterangan", rs.getString("keterangan"))
                                            .build();

                                    URL = link + "/antrean/batal";

                                    response = exchangeMobileJKN(URL, requestJson);
                                    if (response == null) {
                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                    }

                                    metadata = (Map<String, Object>) response.getBody().get("metadata");

                                    if (metadata.get("code").toString().equals("200")) {
                                        Sequel.queryu2("update referensi_mobilejkn_bpjs_batal set statuskirim='Sudah' where nomorreferensi='" + rs.getString("nomorreferensi") + "'");
                                        datajam = rs.getString("tanggalbatal");
                                        if (!datajam.equals("")) {
                                            if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "99", datajam}) == true) {
                                                parsedDateTime = dateTimeFormat.parse(datajam);
                                                userTableModel.tambahData("Menjalankan WS taskid batal pelayanan poli Mobile JKN Pasien BPJS");
                                                try {
                                                    requestJson = JsonUtil.createObject()
                                                            .put("kodebooking", rs.getString("nobooking"))
                                                            .put("taskid", "99")
                                                            .put("waktu", parsedDateTime.getTime())
                                                            .build();

                                                    URL = link + "/antrean/updatewaktu";

                                                    response = exchangeMobileJKN(URL, requestJson);
                                                    if (response == null) {
                                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                    }

                                                    metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                    if (!metadata.get("code").toString().equals("200")) {
                                                        Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='99' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                    }
                                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                } catch (Exception ex) {
                                                    System.out.println("Notifikasi Bridging : " + ex);
                                                    SystemLogger.error(ex);
                                                }
                                            }
                                        }
                                    }
                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                } catch (Exception ex) {
                                    System.out.println("Notifikasi Bridging : " + ex);
                                    SystemLogger.error(ex);
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : " + ex);
                            SystemLogger.error(ex);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }

                        ps = koneksi.prepareStatement(
                                "SELECT referensi_mobilejkn_bpjs.nobooking,referensi_mobilejkn_bpjs.no_rawat,reg_periksa.no_rkm_medis,pasien.nm_pasien,referensi_mobilejkn_bpjs.nohp,referensi_mobilejkn_bpjs.nomorkartu,"
                                + "referensi_mobilejkn_bpjs.nik,referensi_mobilejkn_bpjs.tanggalperiksa,poliklinik.nm_poli,dokter.nm_dokter,referensi_mobilejkn_bpjs.jampraktek,"
                                + "referensi_mobilejkn_bpjs.jeniskunjungan,referensi_mobilejkn_bpjs.nomorreferensi,referensi_mobilejkn_bpjs.status,referensi_mobilejkn_bpjs.validasi,"
                                + "referensi_mobilejkn_bpjs.kodepoli,referensi_mobilejkn_bpjs.pasienbaru,referensi_mobilejkn_bpjs.kodedokter,referensi_mobilejkn_bpjs.jampraktek,"
                                + "referensi_mobilejkn_bpjs.nomorantrean,referensi_mobilejkn_bpjs.angkaantrean,referensi_mobilejkn_bpjs.estimasidilayani,referensi_mobilejkn_bpjs.sisakuotajkn,"
                                + "referensi_mobilejkn_bpjs.kuotajkn,referensi_mobilejkn_bpjs.sisakuotanonjkn,referensi_mobilejkn_bpjs.kuotanonjkn "
                                + "FROM referensi_mobilejkn_bpjs INNER JOIN reg_periksa ON referensi_mobilejkn_bpjs.no_rawat=reg_periksa.no_rawat "
                                + "INNER JOIN pasien ON reg_periksa.no_rkm_medis=pasien.no_rkm_medis "
                                + "INNER JOIN poliklinik ON reg_periksa.kd_poli=poliklinik.kd_poli "
                                + "INNER JOIN dokter ON reg_periksa.kd_dokter=dokter.kd_dokter "
                                + "WHERE referensi_mobilejkn_bpjs.statuskirim='Sudah' and referensi_mobilejkn_bpjs.tanggalperiksa between '" + Tanggal1.getText() + "' and '" + Tanggal2.getText() + "' "
                                + "order by referensi_mobilejkn_bpjs.tanggalperiksa");
                        try {
                            rs = ps.executeQuery();
                            SystemLogger.sql(ps.toString());
                            while (rs.next()) {
                                datajam = Sequel.cariIsi("select mutasi_berkas.dikirim from mutasi_berkas where mutasi_berkas.no_rawat=? and mutasi_berkas.dikirim<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "3", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid mulai tunggu poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "3")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='3' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }

                                datajam = Sequel.cariIsi("select mutasi_berkas.diterima from mutasi_berkas where mutasi_berkas.no_rawat=? and mutasi_berkas.diterima<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "4", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid mulai pelayanan poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "4")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='4' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }

                                datajam = Sequel.cariIsi("select concat(pemeriksaan_ralan.tgl_perawatan,' ',pemeriksaan_ralan.jam_rawat) from pemeriksaan_ralan where pemeriksaan_ralan.no_rawat=?", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "5", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid selesai pelayanan poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "5")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='5' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }

                                noresep = Sequel.cariIsi("select resep_obat.no_resep from resep_obat where resep_obat.no_rawat=?", rs.getString("no_rawat"));
                                if (!noresep.equals("")) {
                                    userTableModel.tambahData("Menjalankan WS tambah antrian farmasi Mobile JKN Pasien BPJS");
                                    try {
                                        requestJson = JsonUtil.createObject()
                                                .put("kodebooking", rs.getString("nobooking"))
                                                .put("jenisresep", Sequel.cariInteger("select count(resep_dokter_racikan.no_resep) from resep_dokter_racikan where resep_dokter_racikan.no_resep=?", noresep) > 0 ? "Racikan" : "Non Racikan")
                                                .put("nomorantrean", Integer.parseInt(StringUtils.right(noresep, 4)))
                                                .put("keterangan", "Resep dibuat secara elektronik di poli")
                                                .build();

                                        URL = link + "/antrean/farmasi/add";

                                        response = exchangeMobileJKN(URL, requestJson);
                                        if (response == null) {
                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                        }

                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                    } catch (Exception ex) {
                                        System.out.println("Notifikasi Bridging : " + ex);
                                        SystemLogger.error(ex);
                                    }
                                }

                                datajam = Sequel.cariIsi("select concat(resep_obat.tgl_perawatan,' ',resep_obat.jam) from resep_obat where resep_obat.tgl_perawatan<>'0000-00-00' and resep_obat.status='ralan' and resep_obat.no_rawat=?", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "6", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid permintaan resep poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "6")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='6' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }

                                datajam = Sequel.cariIsi("select concat(resep_obat.tgl_penyerahan,' ',resep_obat.jam_penyerahan) from resep_obat where resep_obat.status='ralan' and resep_obat.no_rawat=? and concat(resep_obat.tgl_penyerahan,' ',resep_obat.jam_penyerahan)<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "7", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid validasi resep poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "7")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='7' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }

                                datajam = Sequel.cariIsi("select now() from reg_periksa where reg_periksa.stts='Batal' and reg_periksa.no_rawat=?", rs.getString("no_rawat"));
                                if (!datajam.equals("")) {
                                    if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "99", datajam}) == true) {
                                        parsedDateTime = dateTimeFormat.parse(datajam);
                                        userTableModel.tambahData("Menjalankan WS taskid batal pelayanan poli Mobile JKN Pasien BPJS");
                                        try {
                                            requestJson = JsonUtil.createObject()
                                                    .put("kodebooking", rs.getString("nobooking"))
                                                    .put("taskid", "99")
                                                    .put("waktu", parsedDateTime.getTime())
                                                    .build();

                                            URL = link + "/antrean/updatewaktu";

                                            response = exchangeMobileJKN(URL, requestJson);
                                            if (response == null) {
                                                throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                            }

                                            metadata = (Map<String, Object>) response.getBody().get("metadata");

                                            if (!metadata.get("code").toString().equals("200")) {
                                                Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='99' and no_rawat='" + rs.getString("no_rawat") + "'");
                                            }
                                            userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                        } catch (Exception ex) {
                                            System.out.println("Notifikasi Bridging : " + ex);
                                            SystemLogger.error(ex);
                                        }
                                    }
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif : " + ex);
                            SystemLogger.error(ex);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }

                        //pasien Non JKN
                        userTableModel.tambahData("Menjalankan WS tambah antrian Mobile JKN Pasien Non BPJS");
                        ps = koneksi.prepareStatement(
                                "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.kd_poli,poliklinik.nm_poli,reg_periksa.stts_daftar,reg_periksa.no_rkm_medis,reg_periksa.kd_pj "
                                + "from reg_periksa inner join dokter on reg_periksa.kd_dokter=dokter.kd_dokter inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.tgl_registrasi between '" + Tanggal1.getText() + "' and '" + Tanggal2.getText() + "' "
                                + "and reg_periksa.no_rawat not in (select referensi_mobilejkn_bpjs.no_rawat from referensi_mobilejkn_bpjs where referensi_mobilejkn_bpjs.tanggalperiksa between '" + Tanggal1.getText() + "' and '" + Tanggal2.getText() + "') "
                                + "order by concat(reg_periksa.tgl_registrasi,' ',reg_periksa.jam_reg)");
                        try {
                            rs = ps.executeQuery();
                            SystemLogger.sql(ps.toString());
                            while (rs.next()) {
                                ps2 = koneksi.prepareStatement("select * from jadwal where jadwal.hari_kerja=? and jadwal.kd_dokter=? and jadwal.kd_poli=?");
                                try {
                                    ps2.setString(1, hari);
                                    ps2.setString(2, rs.getString("kd_dokter"));
                                    ps2.setString(3, rs.getString("kd_poli"));
                                    rs2 = ps2.executeQuery();
                                    SystemLogger.sql(ps2.toString());
                                    if (rs2.next()) {
                                        kodedokter = Sequel.cariIsi("select maping_dokter_dpjpvclaim.kd_dokter_bpjs from maping_dokter_dpjpvclaim where maping_dokter_dpjpvclaim.kd_dokter=?", rs.getString("kd_dokter"));
                                        kodepoli = Sequel.cariIsi("select maping_poli_bpjs.kd_poli_bpjs from maping_poli_bpjs where maping_poli_bpjs.kd_poli_rs=?", rs.getString("kd_poli"));
                                        if ((!kodedokter.equals("")) && (!kodepoli.equals(""))) {
                                            try {
                                                datajam = Sequel.cariIsi("select DATE_ADD(concat('" + rs.getString("tgl_registrasi") + "',' ','" + rs2.getString("jam_mulai") + "'),INTERVAL " + (Integer.parseInt(rs.getString("no_reg")) * 5) + " MINUTE) ");
                                                parsedDateTime = dateTimeFormat.parse(datajam);
                                                if (!rs.getString("kd_pj").equals(kodebpjs)) {
                                                    requestJson = JsonUtil.createObject()
                                                            .put("kodebooking", rs.getString("no_rawat"))
                                                            .put("jenispasien", "NON JKN")
                                                            .put("nomorkartu", "-")
                                                            .put("nik", "-")
                                                            .put("nohp", "-")
                                                            .put("kodepoli", kodepoli)
                                                            .put("namapoli", rs.getString("nm_poli"))
                                                            .put("pasienbaru",
                                                                    rs.getString("stts_daftar")
                                                                            .replace("Baru", "1")
                                                                            .replace("Lama", "0")
                                                                            .replace("-", "0")
                                                            )
                                                            .put("norm", rs.getString("no_rkm_medis"))
                                                            .put("tanggalperiksa", rs.getString("tgl_registrasi"))
                                                            .put("kodedokter", kodedokter)
                                                            .put("namadokter", rs.getString("nm_dokter"))
                                                            .put("jampraktek",
                                                                    rs2.getString("jam_mulai").substring(0, 5)
                                                                    + "-"
                                                                    + rs2.getString("jam_selesai").substring(0, 5)
                                                            )
                                                            .put("jeniskunjungan", 3)
                                                            .put("nomorreferensi", "-")
                                                            .put("nomorantrean", rs.getString("no_reg"))
                                                            .put("angkaantrean", Integer.parseInt(rs.getString("no_reg")))
                                                            .put("estimasidilayani", parsedDateTime.getTime())
                                                            .put("sisakuotajkn", rs2.getInt("kuota") - Integer.parseInt(rs.getString("no_reg")))
                                                            .put("kuotajkn", rs2.getInt("kuota"))
                                                            .put("sisakuotanonjkn", rs2.getInt("kuota") - Integer.parseInt(rs.getString("no_reg")))
                                                            .put("kuotanonjkn", rs2.getInt("kuota"))
                                                            .put("keterangan", "Peserta harap 30 menit lebih awal guna pencatatan administrasi.")
                                                            .build();

                                                    URL = link + "/antrean/add";

                                                    response = exchangeMobileJKN(URL, requestJson);
                                                    if (response == null) {
                                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                    }

                                                    metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                }
                                            } catch (Exception ex) {
                                                System.out.println("Notifikasi Bridging : " + ex);
                                                SystemLogger.error(ex);
                                            }

                                            datajam = Sequel.cariIsi("select mutasi_berkas.dikirim from mutasi_berkas where mutasi_berkas.no_rawat=? and mutasi_berkas.dikirim<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "3", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid mulai tunggu poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "3")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='3' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }

                                            datajam = Sequel.cariIsi("select mutasi_berkas.diterima from mutasi_berkas where mutasi_berkas.no_rawat=? and mutasi_berkas.diterima<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "4", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid mulai pelayanan poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "4")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='4' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }

                                            datajam = Sequel.cariIsi("select concat(pemeriksaan_ralan.tgl_perawatan,' ',pemeriksaan_ralan.jam_rawat) from pemeriksaan_ralan where pemeriksaan_ralan.no_rawat=?", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "5", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid selesai pelayanan poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "5")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='5' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }

                                            noresep = Sequel.cariIsi("select resep_obat.no_resep from resep_obat where resep_obat.no_rawat=?", rs.getString("no_rawat"));
                                            if (!noresep.equals("")) {
                                                userTableModel.tambahData("Menjalankan WS tambah antrian farmasi Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                try {
                                                    requestJson = JsonUtil.createObject()
                                                            .put("kodebooking", rs.getString("no_rawat"))
                                                            .put("jenisresep", Sequel.cariInteger("select count(resep_dokter_racikan.no_resep) from resep_dokter_racikan where resep_dokter_racikan.no_resep=?", noresep) > 0 ? "Racikan" : "Non Racikan")
                                                            .put("nomorantrean", Integer.parseInt(StringUtils.right(noresep, 4)))
                                                            .put("keterangan", "Resep dibuat secara elektronik di poli")
                                                            .build();

                                                    URL = link + "/antrean/farmasi/add";

                                                    response = exchangeMobileJKN(URL, requestJson);
                                                    if (response == null) {
                                                        throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                    }

                                                    metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                    userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                } catch (Exception ex) {
                                                    System.out.println("Notifikasi Bridging : " + ex);
                                                    SystemLogger.error(ex);
                                                }
                                            }

                                            datajam = Sequel.cariIsi("select concat(resep_obat.tgl_perawatan,' ',resep_obat.jam) from resep_obat where resep_obat.tgl_perawatan<>'0000-00-00' and resep_obat.status='ralan' and resep_obat.no_rawat=?", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "6", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid permintaan resep poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "6")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='6' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }

                                            datajam = Sequel.cariIsi("select concat(resep_obat.tgl_penyerahan,' ',resep_obat.jam_penyerahan) from resep_obat where resep_obat.status='ralan' and resep_obat.no_rawat=? and concat(resep_obat.tgl_penyerahan,' ',resep_obat.jam_penyerahan)<>'0000-00-00 00:00:00'", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "7", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid validasi resep poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "7")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='7' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }

                                            datajam = Sequel.cariIsi("select now() from reg_periksa where reg_periksa.stts='Batal' and reg_periksa.no_rawat=?", rs.getString("no_rawat"));
                                            if (!datajam.equals("")) {
                                                if (Sequel.menyimpantf2("referensi_mobilejkn_bpjs_taskid", "?,?,?", "task id", 3, new String[]{rs.getString("no_rawat"), "99", datajam}) == true) {
                                                    parsedDateTime = dateTimeFormat.parse(datajam);
                                                    userTableModel.tambahData("Menjalankan WS taskid batal pelayanan poli Mobile JKN Pasien Non BPJS/BPS Onsite");
                                                    try {
                                                        requestJson = JsonUtil.createObject()
                                                                .put("kodebooking", rs.getString("no_rawat"))
                                                                .put("taskid", "99")
                                                                .put("waktu", parsedDateTime.getTime())
                                                                .build();

                                                        URL = link + "/antrean/updatewaktu";

                                                        response = exchangeMobileJKN(URL, requestJson);
                                                        if (response == null) {
                                                            throw new IllegalStateException(String.format("Response WS BPJS {'%s'} kosong / null", URL));
                                                        }

                                                        metadata = (Map<String, Object>) response.getBody().get("metadata");

                                                        if (!metadata.get("code").toString().equals("200")) {
                                                            Sequel.queryu2("delete from referensi_mobilejkn_bpjs_taskid where taskid='99' and no_rawat='" + rs.getString("no_rawat") + "'");
                                                        }
                                                        userTableModel.tambahData("respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                                                    } catch (Exception ex) {
                                                        System.out.println("Notifikasi Bridging : " + ex);
                                                        SystemLogger.error(ex);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                } catch (Exception ex) {
                                    System.out.println("Notif : " + ex);
                                    SystemLogger.error(ex);
                                } finally {
                                    if (rs2 != null) {
                                        rs2.close();
                                    }
                                    if (ps2 != null) {
                                        ps2.close();
                                    }
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : " + ex);
                            SystemLogger.error(ex);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }
                        userTableModel.tambahData("Proses update selesai");
                    } catch (Exception ez) {
                        System.out.println("Notif : " + ez);
                        SystemLogger.error(ez);
                    }
                }
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
}
