/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsservicesirsyankes;

import fungsi.HttpRequestUtil;
import fungsi.JsonUtil;
import fungsi.LogTableModel;
import fungsi.SIRSSecurityUtil;
import fungsi.koneksiDB;
import fungsi.logger.LogType;
import fungsi.logger.SystemLogger;
import fungsi.sekuel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private sekuel Sequel = new sekuel();
    private String URL = "";
    private SIRSSecurityUtil security = new SIRSSecurityUtil(koneksiDB.IDSIRS(), koneksiDB.PASSSIRS());
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceSIRSYankes.logPath, "app-log");
    private final int UPDATE_INTERVAL_MINUTES = 5;

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        koneksiDB.condb();
        initComponents();
        try {
            URL = koneksiDB.URLAPISIRS();
        } catch (Exception e) {
            System.out.println("E : " + e);
            SystemLogger.error(e);
        }

        this.setSize(390, 340);

        startScheduler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service SIRANAP");

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setMaximumSize(null);

        jTable1.setModel(userTableModel);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new frmUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void startScheduler() {
        ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();

        Runnable task = () -> {
            LocalTime now = LocalTime.now();

            if (now.equals(LocalTime.of(0, 0, 0))) {
                SwingUtilities.invokeLater(() -> {
                    userTableModel.resetData();
                    SystemLogger.reconfigure();
                    System.out.println("Daily log reset at " + now.toString());
                });
            }

            if (now.getMinute() % UPDATE_INTERVAL_MINUTES == 0 && now.getSecond() == 0) {
                updateSiranap();
            }
        };
        scheduler.scheduleAtFixedRate(task, 0, 1, TimeUnit.SECONDS);
    }

    private void updateSiranap() {
        try (Connection conn = koneksiDB.condb(); PreparedStatement ps = conn.prepareStatement(
                "SELECT k.kode_ruang_siranap, k.kelas_ruang_siranap, k.kd_bangsal, "
                + "b.nm_bangsal, k.kelas, k.kapasitas, k.tersedia, k.tersediapria, "
                + "k.tersediawanita, k.menunggu "
                + "FROM siranap_ketersediaan_kamar k "
                + "INNER JOIN bangsal b ON k.kd_bangsal = b.kd_bangsal"
        ); ResultSet rs = ps.executeQuery()) {
            SwingUtilities.invokeLater(() -> userTableModel.tambahData("Memulai update Siranap"));

            while (rs.next()) {
                try {
                    String kodeRuang = rs.getString("kode_ruang_siranap");
                    String namaBangsal = rs.getString("nm_bangsal");
                    SwingUtilities.invokeLater(() -> userTableModel.tambahData("Mengirim kamar " + kodeRuang + " " + namaBangsal));

                    int total = Sequel.cariInteger("SELECT COUNT(kd_kamar) FROM kamar " + "WHERE statusdata='1' AND kelas='" + rs.getString("kelas") + "' " + "AND kd_bangsal='" + rs.getString("kd_bangsal") + "'");
                    int terpakai = Sequel.cariInteger("SELECT COUNT(kd_kamar) FROM kamar " + "WHERE statusdata='1' AND kelas='" + rs.getString("kelas") + "' AND status='ISI' " + "AND kd_bangsal='" + rs.getString("kd_bangsal") + "'");

                    SIRSSecurityUtil.SignatureResult resultSignature = security.generateSignaturePair();
                    HttpHeaders headers = new HttpHeaders();
                    headers.add("X-rs-id", resultSignature.rsId);
                    headers.add("X-pass", resultSignature.md5pass);
                    headers.add("X-Timestamp", String.valueOf(resultSignature.timestamp));
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    
//                  TODO: align implementation with latest API documentation
                    String requestJson = JsonUtil.createObject()
                            .put("id_tt", rs.getString("kelas_ruang_siranap").substring(0, 4))
                            .put("jumlah_ruang", "")
                            .put("jumlah", String.valueOf(total))
                            .put("terpakai", String.valueOf(terpakai))
                            .build();

                    ResponseEntity<Map> response = HttpRequestUtil.getInstance().exchange(URL, HttpMethod.POST, requestJson, Map.class, headers);

                    SwingUtilities.invokeLater(() -> {
                        userTableModel.tambahData("Request URL: " + URL, LogType.HTTP);
                        userTableModel.tambahData("Request JSON: " + requestJson, LogType.HTTP);
                        userTableModel.tambahData("Respon WS SIRS: " + response.getBody(), LogType.HTTP);
                    });
                } catch (Exception ex) {
                    SystemLogger.error(ex);
                    System.out.println(ex);
                }
            }
            SwingUtilities.invokeLater(() -> userTableModel.tambahData("Proses update selesai"));
        } catch (Exception e) {
            SystemLogger.error(e);
            System.out.println(e);
        }
    }

}
