package khanzahmsserviceaplicare;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalTime;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
import khanzautils.HttpRequestUtil;
import khanzautils.LogTableModel;
import khanzautils.bpjs.AplicareHelper;
import khanzautils.bpjs.BPJSSecurityUtil;
import khanzautils.koneksiDB;
import khanzautils.logger.LogType;
import khanzautils.logger.SystemLogger;
import khanzautils.sekuel;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {

    private Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private String URL = "", link = "";
    private final String kodeppk = Sequel.cariIsi("select setting.kode_ppk from setting");
    private HttpHeaders headers;
    private BPJSSecurityUtil security = new BPJSSecurityUtil(koneksiDB.CONSIDAPIBPJS(), koneksiDB.SECRETKEYAPIBPJS(), koneksiDB.USERKEYAPIBPJS());
    private Map<String, Object> metadata;
    private LogTableModel userTableModel = new LogTableModel(KhanzaHMSServiceAplicare.logPath, "app-log");
    private final int UPDATE_INTERVAL_MINUTES = 5;

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        try {
            link = koneksiDB.URLAPIAPLICARE();
        } catch (Exception e) {
            System.out.println("E : " + e);
            SystemLogger.error(e);
        }

        this.setSize(490, 340);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(210);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(210);

        startScheduler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service Aplicare");

        jButton1.setText("Keluar");
        jButton1.setMaximumSize(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 402));

        jTable1.setModel(userTableModel);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            SystemLogger.error(ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new frmUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void startScheduler() {
        ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();

        Runnable task = () -> {
            LocalTime now = LocalTime.now();

            if (now.equals(LocalTime.of(0, 0, 0))) {
                userTableModel.resetData();
                SystemLogger.reconfigure();
                System.out.println("Daily log reset at " + now.toString());
            }

            if (now.getMinute() % UPDATE_INTERVAL_MINUTES == 0 && now.getSecond() == 0) {
                jam();
            }
        };
        scheduler.scheduleAtFixedRate(task, 0, 1, TimeUnit.SECONDS);
    }

    private void jam() {
        try {
            koneksi = koneksiDB.condb();
            userTableModel.tambahData("Memulai update aplicare");
            try (PreparedStatement ps = koneksi.prepareStatement(
                    "SELECT aplicare_ketersediaan_kamar.kode_kelas_aplicare, aplicare_ketersediaan_kamar.kd_bangsal, bangsal.nm_bangsal,"
                    + " COUNT(k.kd_kamar) AS kapasitas, SUM(k.status = 'KOSONG') AS tersedia"
                    + " FROM aplicare_ketersediaan_kamar INNER JOIN bangsal ON aplicare_ketersediaan_kamar.kd_bangsal = bangsal.kd_bangsal"
                    + " LEFT JOIN kamar k ON bangsal.kd_bangsal = k.kd_bangsal AND k.statusdata = '1'"
                    + " GROUP BY aplicare_ketersediaan_kamar.kd_bangsal"
            ); ResultSet rs = ps.executeQuery();) {
                SystemLogger.sql(ps.toString());

                while (rs.next()) {
                    String kodeKelas = rs.getString("kode_kelas_aplicare");
                    String namaBangsal = rs.getString("nm_bangsal");
                    userTableModel.tambahData("Mengirimkan kamar " + kodeKelas + " " + namaBangsal);
                    try {
                        BPJSSecurityUtil.SignatureResult resultSignature = security.generateSignaturePair();
                        headers = new HttpHeaders();
                        headers.setContentType(MediaType.APPLICATION_JSON);
                        headers.add("X-Cons-ID", koneksiDB.CONSIDAPIAPLICARE());
                        headers.add("X-Timestamp", String.valueOf(resultSignature.timestamp));
                        headers.add("X-Signature", resultSignature.signature);

                        int tersedia = rs.getInt("tersedia");
                        int kapasitas = rs.getInt("kapasitas");

                        String requestJson = AplicareHelper.buildUpdateKamarJson(rs.getString("kode_kelas_aplicare"), rs.getString("kd_bangsal"), rs.getString("nm_bangsal"), kapasitas, tersedia, tersedia, tersedia, tersedia);

                        URL = link + "/rest/bed/update/" + kodeppk;

                        HttpRequestUtil http = HttpRequestUtil.getInstance();
                        ResponseEntity<Map> responseEntity = http.exchange(URL, HttpMethod.POST, requestJson, Map.class, headers);

                        Map responseMap = responseEntity.getBody();
                        if (responseMap != null && responseMap.containsKey("metadata")) {
                            metadata = (Map<String, Object>) responseEntity.getBody().get("metadata");
                            userTableModel.tambahData("Request URL: " + URL, LogType.HTTP);
                            userTableModel.tambahData("Request JSON: " + requestJson, LogType.HTTP);
                            userTableModel.tambahData("Respon WS BPJS : " + metadata.get("code").toString() + " " + metadata.get("message").toString());
                        }
                    } catch (Exception ex) {
                        System.out.println("Notifikasi Bridging : " + ex);
                        SystemLogger.error(ex);
                    }
                }
            } catch (Exception ex) {
                System.out.println("Notif Ketersediaan : " + ex);
                SystemLogger.error(ex);
            }
            userTableModel.tambahData("Proses update selesai");
        } catch (Exception ez) {
            System.out.println("Notif : " + ez);
            SystemLogger.error(ez);
        }
    }
}
